shealtielanz

medium

# Unchecked Low-Level Calls.

## Summary
Certain low-level calls were made in the protocol, However, their return value is not checked.
## Vulnerability Detail
An Instance of this issue
```vyper
def withdraw_from_account_eth(_amount: uint256):
    """
    @notice
        Allows a user to withdraw from his WETH margin and
        automatically swaps back to ETH.
    """
    assert self.margin[msg.sender][WETH] >= _amount, "insufficient balance"
    self.margin[msg.sender][WETH] -= _amount
    raw_call(
        WETH,
        concat(
            method_id("withdrawTo(address,uint256)"),
            convert(msg.sender, bytes32),
            convert(_amount, bytes32),
        ),
    )
```
The return value of the low-level call is not checked, so if the call fails, the Ether will be locked in the contract and the user will lose funds.  due to   `self.margin[msg.sender][WETH] -= _amount` .

## Impact
This would lead to operations and functions that utilize these calls to keep going, not minding if those calls were successful or not because if those calls fail, they'll fail silently.
Where the return value of the low-level call is not checked, so if the call fails, the Ether will be locked in the contract. when sending ETH.
## Code Snippet
These are all the known Instances seen in the protocol.
- `1` ~  https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L701C1-L708C6
- `2` ~ https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L667C1-L668C51
- `3` ~ https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L779C1-L779C60
- `4` ~ https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L840C1-L848C6

## Tool used

Manual Review

## Recommendation
Revert the entire transaction if the refund call fails by checking that the success return value of the payable(to).call(...) returns true.